- DATABASES.md
- README.md
This MR intends to fullfill: https://bitovi.atlassian.net/browse/HATCH-219
> feat: create databases.md to show how to use postgres

- DATABASES.md
- README.md
- doc/nextSteps/DATABASES.md
This mr intends to fix indentation problems and have all instances of the word postgres in lowercase.
> fix/refactor: adjust indentation

- README.md
- doc/next-steps/using-postgres-db.md
- packages/react-rest/README.md
This PR contains recommended updates to the react-rest getting started guide
> Updates to react-rest getting started guide

- doc/naming.md
This MR updates the file naming.md as requested in this story: https://bitovi.atlassian.net/browse/HATCH-260
> Hatch-260/update naming.md fix models attributes

- doc/naming.md
- package-lock.json
- packages/koa/src/naming.spec.ts
- packages/koa/src/testing/utils.ts
- packages/node/package.json
- packages/node/src/sequelize/index.ts
This PR intends to fullfill: https://bitovi.atlassian.net/browse/HATCH-267
The tests are not currently passing, though. Will be addressed in future PR, **do not merge**.
> HATCH-267 - feat: ensure schema.name is tested

- packages/koa/src/naming.spec.ts
- packages/node/src/sequelize/index.ts
Quick fix for issue mentioned at slack.
> HATCH-307/chore: validate options existence

- package-lock.json
- packages/react-jsonapi/package.json
- packages/react/package.json
- packages/rest-client-jsonapi/package.json
> HATCH-257 update packages to get regex change in.

- packages/design-mui/package.json
- packages/react-jsonapi/package.json
- packages/react-rest/package.json
- packages/react-ui/package.json
- packages/react/package.json
- packages/rest-client-jsonapi/package.json
- packages/rest-client-jsonapi/src/services/findAll/findAll.ts
- packages/rest-client-jsonapi/src/services/findOne/findOne.ts
- packages/rest-client-jsonapi/src/services/utils/query/query.test.ts
- packages/rest-client-jsonapi/src/services/utils/query/query.ts
- packages/rest-client/package.json
- packages/rest-client/src/services/promise/findAll/findAll.ts
- packages/rest-client/src/services/promise/findOne/findOne.ts
- packages/rest-client/src/services/types/source.ts
> HATCH-113: Allow both fields & include to be passed through as query params

- packages/design-mui/package.json
- packages/react-ui/package.json
- packages/react-ui/src/hatchifyReact/hatchifyReact.tsx
- packages/react-ui/src/react-ui.ts
- packages/react/package.json
- packages/react/src/react.tsx
Jira link: https://bitovi.atlassian.net/browse/HATCH-358
> HATCH-358/Exporting two types that KlearTrust needs

- package-lock.json
- packages/design-mui/package.json
- packages/react-jsonapi/package.json
- packages/react-rest/package.json
- packages/react-rest/src/services/useAll/useAll.ts
- packages/react-ui/package.json
- packages/react/package.json
- packages/rest-client-jsonapi/package.json
Add missing dependency to dependency array in react-rest `useAll`
> Add missing dependency to dependency array in react-rest `useAll`

- packages/koa/src/jsonapi.spec.ts
- packages/node/src/everything/index.ts
- packages/node/src/serialize/index.ts
> [HATCH-333] Always return the instance body on PATCH

- example/hatchify-app/frontend/App.tsx
- package-lock.json
- packages/design-mui/package.json
- packages/react-jsonapi/package.json
- packages/react-rest/package.json
- packages/react-ui/package.json
- packages/react/package.json
- packages/rest-client-jsonapi/package.json
> bump versions

- packages/rest-client-jsonapi/src/services/utils/query/query.test.ts
- packages/rest-client-jsonapi/src/services/utils/query/query.ts
- this error was commented out with previous namespace work to speed up merge for client
- pr simply re-enables error & tests against it
https://bitovi.atlassian.net/browse/HATCH-387
> hatch-387: re-enable error for namespaced fields param

- example/hatchify-app/package-lock.json
- packages/core/src/dataTypes/enumerate/getFinalize.ts
- packages/core/src/dataTypes/enumerate/index.spec.ts
- packages/core/src/dataTypes/string/getFinalize.ts
> HATCH-349/add client side functions

- example/hatchify-app/package-lock.json
- package-lock.json
- packages/core/package.json
- packages/core/src/dataTypes/enumerate/getFinalize.ts
- packages/core/src/dataTypes/enumerate/index.spec.ts
- packages/react-rest/src/services/hatchifyReactRest/hatchifyReactRest.ts
- packages/react-rest/src/services/useUpdateOne/useUpdateOne.test.ts
- packages/react-rest/src/services/useUpdateOne/useUpdateOne.ts
- packages/rest-client-jsonapi/src/services/updateOne/updateOne.test.ts
- packages/rest-client-jsonapi/src/services/updateOne/updateOne.ts
- packages/rest-client/src/services/promise/updateOne/updateOne.test.ts
- packages/rest-client/src/services/promise/updateOne/updateOne.ts
- packages/rest-client/src/services/types/source.ts
> merge main into feature

- packages/core/src/assembler/types.ts
- packages/core/src/dataTypes/enumerate/coerce.ts
- packages/core/src/dataTypes/enumerate/finalizeControl.ts
- packages/core/src/dataTypes/enumerate/getFinalize.ts
- packages/core/src/dataTypes/enumerate/getPartialControl.spec.ts
- packages/core/src/dataTypes/enumerate/getPartialControl.ts
- packages/core/src/dataTypes/enumerate/getPartialOrm.spec.ts
- packages/core/src/dataTypes/enumerate/getPartialOrm.ts
- packages/core/src/dataTypes/enumerate/index.ts
- packages/core/src/dataTypes/enumerate/types.ts
- packages/core/src/dataTypes/enumerate/validateValues.ts
> Hatch 349/update core

- README.md
- packages/create/package.json
- packages/create/template-koa-postgres/frontend/App.tsx
- packages/create/template-koa-sqlite/frontend/App.tsx
> hatch-436: fixlink in readme, add everything to templates

- CONTRIBUTING.md
https://bitovi.atlassian.net/browse/HATCH-316
> hatch-316: document release process

- doc/next-steps/adding-checkboxes-to-the-list.md
- doc/next-steps/customizing-what-is-displayed-in-an-empty-list.md
- example/react-rest-hatchify-backend/vite.config.ts
- packages/react-rest/README.md
Update port number in docs and in images. Also fixes several out of date code examples.
> Update port number

- package-lock.json
- packages/design-mui/package.json
- packages/design-mui/src/components/MuiEverything/MuiEverything.test.tsx
- packages/design-mui/src/components/MuiEverything/MuiEverything.tsx
- packages/react-ui/package.json
- packages/react-ui/src/components/HatchifyEverything/HatchifyEverything.tsx
- packages/react-ui/src/presentation/interfaces.ts
- packages/react/package.json
> Hatch 436/fix splash

- package-lock.json
- packages/design-mui/package.json
- packages/design-mui/src/components/MuiEverything/MuiEverything.tsx
- packages/react-ui/package.json
- packages/react-ui/src/components/HatchifyCollection/HatchifyCollection.tsx
- packages/react-ui/src/components/HatchifyCollection/index.ts
- packages/react-ui/src/components/HatchifyEverything/HatchifyEverything.tsx
- packages/react-ui/src/components/HatchifyEverything/components/NoSchemas.tsx
- packages/react-ui/src/components/HatchifyEverything/components/WithSchemas.tsx
- packages/react-ui/src/components/HatchifyEverything/components/index.ts
- packages/react-ui/src/presentation/interfaces.ts
- packages/react/package.json
https://bitovi.atlassian.net/browse/HATCH-455
> hatch-455: fix default includes for Everything

- package-lock.json
- packages/react-jsonapi/package.json
- packages/react/package.json
- packages/rest-client-jsonapi/package.json
- packages/rest-client-jsonapi/src/services/utils/query/query.test.ts
- packages/rest-client-jsonapi/src/services/utils/query/query.ts
https://bitovi.atlassian.net/browse/HATCH-464
> hatch-464: update null value for filters

- doc/schema/attribute-types/boolean.md
- doc/schema/attribute-types/dateonly.md
- doc/schema/attribute-types/datetime.md
- doc/schema/attribute-types/integer.md
- doc/schema/attribute-types/number.md
- doc/schema/attribute-types/string.md
- doc/schema/attribute-types/text.md
> hatch-484: add dateonly doc, update datetime

- package.json
- packages/react/package.json
- scripts/pree2e.sh
…and broke pree2e.sh into it's own shell script
> fix hatchifyjs/react type export 

- packages/design-mui/package.json
- packages/react-jsonapi/package.json
- packages/react-rest/package.json
- packages/react-ui/package.json
- packages/rest-client-jsonapi/package.json
- packages/rest-client/package.json
Fixed d.ts exports in two other subprojects.
> fix d.ts exports in two other subprojects

- package-lock.json
- packages/design-mui/package.json
- packages/react-jsonapi/package.json
- packages/react-rest/package.json
- packages/react-ui/package.json
- packages/react-ui/src/hooks/useCompoundComponents/helpers/getColumn.test.tsx
- packages/react-ui/src/hooks/useCompoundComponents/helpers/getColumns.test.ts
- packages/react-ui/src/hooks/useCompoundComponents/helpers/getColumnsFromSchema.test.ts
- packages/react-ui/src/hooks/useCompoundComponents/helpers/getColumnsFromSchema.ts
- packages/react/package.json
- packages/rest-client-jsonapi/package.json
- packages/rest-client/package.json
- packages/rest-client/src/rest-client.ts
- packages/rest-client/src/services/utils/records.test.ts
- packages/rest-client/src/services/utils/records.ts
https://bitovi.atlassian.net/browse/HATCH-492
> hatch-492: grid component allows sort on related

- docs/api-documentation.md
- docs/koa/hatchedKoa.serialize.md
- docs/react-jsonapi/README.md
- packages/react-jsonapi/src/react-jsonapi.tsx
- packages/react-rest/src/services/hatchifyReactRest/hatchifyReactRest.ts
> docs: react-jsonapi

- docs/react-jsonapi/README.md
> docs: update react-jsonapi docs function signatures

- package-lock.json
- packages/koa/package.json
- packages/koa/src/hatchify-gsg-seed.ts
adding easy gettng started guide data seeding script
> patch: HATCH-565: add gsg seeding script

- docs/react/hatchedReact.components.datagrid.md
> Datagrid components update

- docs/react-jsonapi/README.md
> docs: react-jsonapi create/update relationships

- README.md
- example/getting-started/backend/index.ts
- example/getting-started/schemas.ts
> fix: add schemas+seed to gsg template

- README.md
> Remove "stop" icon.

- packages/design-mui/package.json
- packages/react-jsonapi/package.json
- packages/react-ui/package.json
Fixing issue with package.json encountered when importing from @hatchify/react in a Node 20.x project.
We will be expanding our bundler and server framework testing matrix which will catch this in the future.
> fix error in package.json module export

- .gitignore
- docs/guides/production-custom-usage.md
> HATCH-527 Update production guide.

- package-lock.json
- packages/express/package.json
- packages/express/src/middleware.spec.ts
- packages/express/src/middleware.ts
Reviewing docs and I had questions so I wrote tests to get answers.
> Add tests for express error handling middleware.

- package-lock.json
- reinstall unbuild to get latest deps to resolve:
> reinstall & bump unbuild dependencies

- packages/react-rest/src/services/useDeleteOne/useDeleteOne.ts
- packages/react-rest/src/services/useUpdateOne/useUpdateOne.ts
- packages/rest-client/src/services/promise/findOne/findOne.ts
- fix missing isPending meta for useUpdateOne, useDeleteOne
- early return in findOne if no data found
> fix: useUpdate/DeleteOne meta for isPending
